/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.senai.Miguel.simuladorrp;

import edu.senai.Miguel.simuladorrpg.model.Equipamento;
import edu.senai.Miguel.simuladorrpg.model.Monstro;
import edu.senai.Miguel.simuladorrpg.classes.jogador;
import java.util.List;
import edu.senai.Miguel.simuladorrpg.service.EquipamentoService;
/**
 *
 * @author Guilherme
 */
public class SimuladorRPG extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimuladorRPG.class.getName());

    /**
     * Creates new form Principal
     */
    public jogador jogador;
    public List<Equipamento> equipamento;
    public SimuladorRPG() {
    jogador = new jogador();
    jogador.setNivel(1);
    equipamento = EquipamentoService.obterEquipamento();
        
                // Pega um monstro específico do enum
        Monstro monstroDaVez = Monstro.ORC_DE_TELEMARKETING;

        // Pega um equipamento
        Equipamento arma = Equipamento.MOTOSSERRA_DA_EVISCERACAO_SANGRENTA;
        Equipamento armadura = Equipamento.ARMADURA_DE_COURO_FALSO;

        // Simula o status do jogador
        int nivelJogador = 5;
        int forcaJogador = nivelJogador + arma.getBonus() + armadura.getBonus();

        System.out.println("Você (Nível " + nivelJogador + ") chuta a porta!");
        System.out.println("Aparece um " + monstroDaVez.getNome() + " de Nível " + monstroDaVez.getNivel() + "!");
        System.out.println("Sua força de combate total é: " + forcaJogador);
        System.out.println("A força do monstro é: " + monstroDaVez.getNivel());
        
        if (forcaJogador > monstroDaVez.getNivel()) {
            System.out.println("\nVITÓRIA! Você derrotou o monstro e pegou o tesouro!");
        } else {
            System.out.println("\nDERROTA! Você precisa fugir para não sofrer coisas ruins!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SimuladorRPG().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
