/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.senai.Miguel.simuladorrp;

import edu.senai.Miguel.simuladorrpg.classes.Equipamento;
import edu.senai.Miguel.simuladorrpg.classes.Jogador;
import edu.senai.Miguel.simuladorrpg.classes.Monstro;
import edu.senai.Miguel.simuladorrpg.services.EquipamentoService;
import edu.senai.Miguel.simuladorrpg.services.MonstroService;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Guilherme
 */
public class SimuladorRPG extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimuladorRPG.class.getName());

    /**
     * Creates new form Principal
     */
    public Jogador jogador;
    public ArrayList<Equipamento> equipamentos;
    public ArrayList<Monstro> monstros;
    public SimuladorRPG() {
        initComponents();
        
        jogador = new Jogador();//Cria Jogador
        jogador.setNivel(1);// Preencher dados Jogador
        equipamentos = (ArrayList<Equipamento>) EquipamentoService.ObterEquipamentos();
        monstros = (ArrayList<Monstro>) MonstroService.ObterMonstros();

        Random r = new Random();
        Monstro m = monstros.get(r.nextInt(0, monstros.size()));
        
        
        System.out.println("Você (Nível " + jogador.getNivel() + ") chuta a porta!");
        System.out.println("Aparece um " + m.getNome()+ " de Nível " + m.getNivel() + "!");
        System.out.println("Sua força de combate total é: " + jogador.getNivel());
        System.out.println("A força do monstro é: " + m.getNivel());
        
        if (jogador.getNivel() > m.getNivel()) {
            System.out.println("\nVITÓRIA! Você derrotou o monstro e pegou o tesouro!");
        } else {
            System.out.println("\nDERROTA! Você precisa fugir para não sofrer coisas ruins!");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *   
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SimuladorRPG().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
