/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.miguelmassane.padaria.Interface;

import edu.miguelmassane.padaria.Produtos;
import edu.miguelmassane.padaria.service.ProdutoService;
import java.util.List;
import javax.swing.DefaultListModel;
import edu.miguelmassane.padaria.produtoVenda;
import java.util.HashSet;
import java.util.Set;
/**
 *
 * @author java
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    List<Produtos> produtos;
    DefaultListModel<produtoVenda> listaCarrinho;
    /**
     * Creates new form Principal'
     */
    public Principal() {
        initComponents();
       produtos = ProdutoService.inicializarProdutos();
        /* produtos.stream()
       .filter(produto -> produto.equals("pao"))
       .
       */
       
        produtos.forEach( item -> {
            listaItens.addItem(item);
        });
       
       listaCarrinho = new DefaultListModel<>();
       Carrinho.setModel(listaCarrinho);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTexto = new javax.swing.JTextArea();
        listaItens = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        Carrinho = new javax.swing.JList<>();
        bRemove = new javax.swing.JButton();
        tTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adicionar.setText("add");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        tTexto.setColumns(20);
        tTexto.setRows(5);
        jScrollPane2.setViewportView(tTexto);

        listaItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaItensActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jScrollPane1.setViewportView(Carrinho);

        bRemove.setText("Remover");
        bRemove.setActionCommand("jButton3");
        bRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveActionPerformed(evt);
            }
        });

        tTotal.setText("Total");
        tTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo");

        tSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(adicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(bRemove)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tSaldo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(listaItens, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRemove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
      
// TODO add your handling code here:
        double Total = ((Produtos)listaItens.getSelectedItem())
                .getPreco() * 
                Integer.parseInt(jSpinner1
                .getValue()
                .toString());
        tTexto.append(
        jSpinner1.getValue().toString()
        + "x"
        + listaItens
        .getSelectedItem()
        .toString()
        + "="
        + Total);
        tTexto.append("\n");
        
        produtoVenda pVenda = new produtoVenda();
        pVenda.setProduto((Produtos) listaItens.getSelectedItem());
        pVenda.setQuantidade(Integer.parseInt(jSpinner1.getValue().toString()));
        pVenda.setTotal();
        total();
        
        int quantidade = Integer.parseInt(
                         jSpinner1.getValue().toString());
        Produtos produto = (Produtos)listaItens.getSelectedItem();
        if (produto.getSaldoEstoque() >= quantidade){
            produtoVenda p = new produtoVenda();
            p.setProduto(produto);
            p.setQuantidade(quantidade);
            p.setTotal();
            listaCarrinho.addElement(pVenda);
           
        }
         atualizaSaldo();
     
    }//GEN-LAST:event_adicionarActionPerformed
    public void total () {
        double total =0; 
        for (int i =0 ; i< listaCarrinho.getSize(); i++) {
           total += listaCarrinho.getElementAt(i).getTotal();
           tTotal.setText("Total:" + total);
        }
    }
    public void atualizaSaldo() {
        tSaldo.setText(Integer.toString(((Produtos)listaItens.getSelectedItem()).getSaldoEstoque()));
    }
    private void bRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveActionPerformed
        // TODO add your handling code here:
        produtoVenda p; 
        if (Carrinho.getSelectedIndex() >=0) {
        p = listaCarrinho.remove(
        listaItens.getSelectedIndex());
        
        p.getProduto().setSaldoEstoque(
                p.getProduto().getSaldoEstoque() + p.getQuantidade());
        atualizaSaldo();
             total();
        }
    }//GEN-LAST:event_bRemoveActionPerformed

    private void tTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalActionPerformed
     
    }//GEN-LAST:event_tTotalActionPerformed

    private void tSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSaldoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tSaldoActionPerformed

    private void listaItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaItensActionPerformed
            tSaldo.setText(Integer.toString((
                (Produtos)listaItens
                        .getSelectedItem()).getSaldoEstoque())
        );
    
    }//GEN-LAST:event_listaItensActionPerformed
   
    /**
     * @param args the command line arguments55
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<produtoVenda> Carrinho;
    private javax.swing.JButton adicionar;
    private javax.swing.JButton bRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<Produtos> listaItens;
    private javax.swing.JTextField tSaldo;
    private javax.swing.JTextArea tTexto;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables
}
